apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-repo-external
  namespace: default
spec:
  target:
    name: backup-repo-external
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        password: |-
          {{ .password }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7e9b8ecb-1586-4f85-a615-b3dd0013c353
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials-external
  namespace: default
spec:
  target:
    name: minio-credentials-external
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 58e193d0-fd57-4332-86a4-b3dd0013e071
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 58e193d0-fd57-4332-86a4-b3dd0013e071
        property: password
