---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8up
  namespace: default
spec:
  interval: 24h
  url: https://k8up-io.github.io/k8up
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: k8up
      version: "4.8.4"
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: default
      interval: 12h

