---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule-backups
  namespace: default
spec:
  backend:
    s3:
      endpoint: http://192.168.1.27:9768
      bucket: backups
      accessKeyIDSecretRef:
        name: minio-credentials
        key: username
      secretAccessKeySecretRef:
        name: minio-credentials
        key: password
    repoPasswordSecretRef:
      name: backup-repo
      key: password
  backup:
    # schedule: '5 4 * * *'
    schedule: '30 21 * * *' # tesing
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    promURL: http://prometheus-prometheus-pushgateway:9091
  check:
    schedule: '0 1 * * 1'
  prune:
    schedule: '0 1 * * 0'
    retention:
      keepLast: 5
      keepDaily: 14