apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m0s
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: "4.1.2"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 1m
  values:
    localpv-provisioner:
      localpv:
        image:
          registry: quay.io/
      hostpathClass:
        name: openebs-hostpath
      helperPod:
        image:
          registry: quay.io/
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: true
          keep: true
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: false
    mayastor:
      enabled: true
      csi:
        node:
          initContainers:
            enabled: false
      io_engine:
        envcontext: "iova-mode=pa"
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true

