apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m0s
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 1m
  values:
    # Refer to https://github.com/openebs/zfs-localpv/blob/HEAD/deploy/helm/charts/values.yaml for complete set of values.
    zfs-localpv:
      enabled: false
      crds:
        zfsLocalPv:
          enabled: false
        csi:
          volumeSnapshots:
            enabled: false
      
    # Refer to https://github.com/openebs/lvm-localpv/blob/HEAD/deploy/helm/charts/values.yaml for complete set of values.
    lvm-localpv:
      enabled: false
      crds:
        lvmLocalPv:
          enabled: false
        csi:
          volumeSnapshots:
            enabled: false

    # Refer to https://github.com/openebs/mayastor-extensions/blob/v2.7.0/chart/values.yaml for complete set of values.
    mayastor:
      enabled: true
      csi:
        node:
          initContainers:
            enabled: true
      etcd:
        # -- Kubernetes Cluster Domain
        clusterDomain: cluster.local
      localpv-provisioner:
        enabled: false
      crds:
        enabled: false

    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
