apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: replicated-storage
parameters:
  protocol: nvmf
  repl: "3"
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Retain
allowVolumeExpansion: true
