version: '3'

tasks:
  encrypt:
    cmds:
      - sops --e --in-place clusters/production/secrets/secrets.yaml
  dencrypt:
    cmds:
      - sops --d --in-place clusters/production/secrets/secrets.yaml