# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: netshoot-nfs-claim
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
#   storageClassName: "nfs-client"
---
kind: Pod
apiVersion: v1
metadata:
  name: netshoot-1
spec:
  # nodeSelector:
  #   openebs.io/nodeid: control-2
  volumes:
    - name: data
      nfs:
        server: 192.168.1.27
        path: /mnt/user/home-cluster-nfs
  containers:
    - name: netshoot-2
      image: nicolaka/netshoot
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/data"
          name: data
