# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: fio-volume-claim
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
#   storageClassName: "nfs-client"
---
kind: Pod
apiVersion: v1
metadata:
  name: netshoot-2
spec:
  nodeSelector:
    openebs.io/nodeid: control-2
  volumes:
    - name: ms-volume
      persistentVolumeClaim:
        claimName: prowlarr-claim
  containers:
    - name: netshoot-2
      image: nicolaka/netshoot
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/config"
          name: ms-volume
