---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "=6.7.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 1m
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - host: podinfo.basingse.ca
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - podinfo.basingse.ca
        secretName: podinfo-tls-secret
