apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: homebridge-claim
  name: homebridge-claim
spec:
  storageClassName: "replicated-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
