apiVersion: apps/v1
kind: Deployment
metadata:
  name: speakarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speakarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speakarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "100"
            - name: PUID
              value: "99"
            - name: TZ
              value: Etc/UTC
              # https://hotio.dev/containers/readarr/#tags
          image: ghcr.io/hotio/readarr:latest@sha256:cda2e48574e0bceb6e7b608e744a0d24f1fe1118b0f95b0d7de0c895cc4dffa8 
          name: speakarr
          ports:
            - containerPort: 8787
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: speakarr-config
            - mountPath: /data
              name: speakarr-media
          livenessProbe:
            exec:
              command:
              - ls
              - /data/
            initialDelaySeconds: 10
            periodSeconds: 7200
            failureThreshold: 1
            timeoutSeconds: 5
      restartPolicy: Always
      volumes:
        - name: speakarr-config
          persistentVolumeClaim:
            claimName: speakarr-config
        - name: speakarr-media
          persistentVolumeClaim:
            claimName: media-pvc
