apiVersion: apps/v1
kind: Deployment
metadata:
  name: speakarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speakarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speakarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: ghcr.io/hotio/readarr:latest@sha256:5cfd2f6d6bc1b89fe827f3cfa59b1920522c1dfbf17a0560f992280baf133c39 
          name: speakarr
          ports:
            - containerPort: 8787
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: speakarr-config
            - mountPath: /data
              name: speakarr-media
      restartPolicy: Always
      volumes:
        - name: speakarr-config
          persistentVolumeClaim:
            claimName: speakarr-config
        - name: speakarr-media
          persistentVolumeClaim:
            claimName: media-pvc
