apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: orbital-sync
  name: orbital-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orbital-sync
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: orbital-sync
    spec:
      containers:
        - env:
            - name: INTERVAL_MINUTES
              value: "20"
            - name: PRIMARY_HOST_BASE_URL
              value: http://192.168.1.3
            - name: PRIMARY_HOST_PASSWORD
              value: Ssh2017!
            - name: SECONDARY_HOSTS_1_BASE_URL
              value: http://pihole.lab
            - name: SECONDARY_HOSTS_1_PASSWORD
              value: Ssh2017!
          image: mattwebbio/orbital-sync:1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          name: orbital-sync
      restartPolicy: Always
