apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: orbital-sync
  name: orbital-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orbital-sync
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: orbital-sync
    spec:
      containers:
        - env:
            - name: INTERVAL_MINUTES
              value: "20"
          image: mattwebbio/orbital-sync:1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          name: orbital-sync
      restartPolicy: Always
