apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: maintainerr-claim
  name: maintainerr-claim
spec:
  storageClassName: "replicated-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
