apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      version: "2.24.0"
  test:
    enable: false
  values:
    adminPassword: "umaid!"
    dnsmasq:
      customDnsEntries:
        - address=/kind-k8s.lab/192.168.3.2
    ingress:
      hosts:
        - pihole.lab
          # paths:  
          #   - path: /
          #     pathType: ImplementationSpecific
