apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      version: "2.24.1"
  test:
    enable: false
  values:
    adminPassword: "Ssh2017!"
    ingress:
      hosts:
        - pihole.lab
          # paths:
          #   - path: /
          #     pathType: ImplementationSpecific
