apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      version: "2.24.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: pihole.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
