# Reference to Helm repository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace:  external-secrets
spec:
  interval: 10m
  url: https://charts.external-secrets.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets
  namespace:  external-secrets
spec:
  interval: 10m
  ref:
    tag: v0.20.4
  url: https://github.com/external-secrets/external-secrets
