---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  chart:
    spec:
      version: "4.0.18"
  values:
    nfs:
      server: 192.168.1.27
      path: /home-cluster-nfs
