---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  values:
    nfs:
      server: 192.168.1.27
      path: /mnt/user/home-cluster-nfs
      reclaimPolicy: Retain
  storageClass:
    create: true
    defaultClass: true
    name: nfs-client
    allowVolumeExpansion: true
    reclaimPolicy: Delete
    archiveOnDelete: true
    pathPattern: "${.PVC.namespace}-${.PVC.name}"
