---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: porkbun-api-keys:reader
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["porkbun-api-keys"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun-webhook:key-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: porkbun-api-keys:reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: porkbun-basingse-porkbun-webhook
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  interval: 5m
  url: https://github.com/mdonoughe/porkbun-webhook
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !deploy/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  interval: 1m
  releaseName: porkbun-basingse
  chart:
    spec:
      chart: deploy/porkbun-webhook/
      sourceRef:
        kind: GitRepository
        name: porkbun-webhook
  values:
    groupName: basingse.ca 
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: umaidabbasi@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - selector:
          dnsZones:
            - basingse.ca 
        dns01:
          webhook:
            groupName: basingse.ca
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-api-keys
                key: api-key
              secretKeySecretRef:
                name: porkbun-api-keys
                key: secret-key