apiVersion: v1
kind: Secret
metadata:
    name: porkbun-api-keys
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:StTNJ4GngkCmGyUZFE1dIJjisI98BQ5R95vQu3V8D4H+BkbIbtYXApq2vmcwxO436Lplj72oBq3Lk9xZGXyPiMpnId0=,iv:mGKpCABNwNKHRgAvqjidAIS458ZvU4Fal84jFVx1LYU=,tag:I6TsBlLgcDt8sG2Y5YPiBw==,type:str]
    secret-key: ENC[AES256_GCM,data:zu2/ybtiRBCcbbolHi3rq+uaXi90v6NyXBtDgpgkZVE9/wh/XpEYh46zTmsFLXFWzv0+Th9TrdmIgT26vaCVkkdmOYo=,iv:98mgPDzmgS8Lvyet2HDKbcj8eO6N4iYmTpcapM0C4pg=,tag:Vpzr9mmWCruYD3MpdtrvvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-12T17:13:48Z"
    mac: ENC[AES256_GCM,data:hwftCdYrpqlmLpvTOjMX50lWL562aao+G4rFlTQPt0cxBkJUS/CEyG91qNiU5vn0WQAk+4joLHWXwtRe2JQDsRt2YXEhfci1ppQvehEeoBzjEyPuolssQizuzkbQUAuBBkqEVOiBZHWp9i8EHlhRT0JPyhmyMBBC9U/lVVhQURY=,iv:O81GK/7gde5aAhqWq2eAM3lV4TM0xQCeOsa127HfDpY=,tag:6+/3a3Sl7o2RwhmN7QF2sQ==,type:str]
    pgp:
        - created_at: "2024-07-12T17:13:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVxt8ZNZv4DAQ/8DTZl5p/56LWWO+yF2rgsLfEQcFOd5FigyPNlKtQkaag9
            M700xVnjH+R3T2G2DIItREGA/tOHSTxayQGx9cGC1aeES+EAZOjg2pRt36AggDjY
            HWy6OZGlfbsxGrjx3eOSLqekb7WH+cGDymSDSa32oBRSgXKW6SK0z41LdJJl4LYN
            Y1OZ9ocGzq2pZ/AEuqfzYY8aXbftBf9l7/eyOX/7/j3HHhEn7bAE/1/B/9yrLYTm
            Qxu3uqKFXIq/SVAqNrDVgT0zKnLvrEemGcW3KAnjxslE7bRXh/6vCZD3pWrw1u6D
            ZzBVj/csXOQv9DIsmU+dSF4O0EnYoXzsKaOTPCvDPZgzTVSrmedtorlgbAdCFtrE
            UiPOh6ZCpKEaK1cRz073x5crcHc+CnQ3ghEQUOIzT0Jrf1XM4r+kF5tymsJye5MG
            1UtJ7bYXbEopAGNFTHtLmwMraylRTCstVISi+iVPxSxNOYyLtD1paEiIVwzmR1vt
            xD3F5CTvf3g9VgKoEdGPe4TU4PYXz8r7N2QLDLtiZZzlOyLpTp8XNJo6LoMQD2RC
            G6DrG/lfYAiJh++IfMu6IAePHp5tLhJBw+minWpZQ644LFuQ1DMpFwFFKb+gyAuT
            EJspR+Dr7C4fEIPYpW+PC6O1tkF8pI3MbQoft76rHsnoDmrWCoNsyzzX61Ok41jU
            aAEJAhBhhaIZG6HPrajPSxDPGBbnKUHPu+HMHYS94F4yE8VLlnIvLmW4BfER2zKk
            Z6zST5qwl8A1RIdD8FE8wdkSSJ88CtJ+fsfooClLmLVyT3aN4RaokKdjQtCDFxox
            5DRWHxT49aLb
            =ok0E
            -----END PGP MESSAGE-----
          fp: BAFBAF486E2E489700A8639C2B75A847B165ECC2
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
