apiVersion: v1
kind: Service
metadata:
  name: readarr
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8787
  selector:
    app: readarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.org/client-max-body-size: "0"
    nginx.org/proxy-buffer-size: 128k
    nginx.org/proxy-buffers: "4 256k"
    nginx.org/location-snippets: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
  labels:
    app: readarr
  name: readarr
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: readarr.basingse.ca
    http:
      paths:
      - backend:
          service:
            name: readarr
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - readarr.basingse.ca
    secretName: readarr-tls-secret
status:
  loadBalancer:
    ingress:
    - ip: 192.168.2.11