apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
spec:
  storageClassName: "replicated-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

