kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  homebridge-claim
  # Optional:
  namespace: default
  # annotations:
    # set to "true" to include in future backups
    # k8up.io/backup: ""
  # Optional:
  #labels:
  #  app: multi-file-writer
spec:
  # Optional:
  storageClassName: replicated-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Must be sufficient to hold your data
      storage: 100Mi
---
apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: homebridge-restore
  namespace: default
spec:
  podSecurityContext:
    fsGroup: 65532
    fsGroupChangePolicy: OnRootMismatch
  snapshot: "fffdc5e6"
  restoreMethod:
    folder:
      claimName: homebridge-claim
  backend:
    s3:
      endpoint: http://192.168.1.27:9768
      bucket: backups
      accessKeyIDSecretRef:
        name: minio-credentials
        key: username
      secretAccessKeySecretRef:
        name: minio-credentials
        key: password
    repoPasswordSecretRef:
      name: backup-repo
      key: password