---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
  releaseName: pihole
  dependsOn:
    - name: pihole