apiVersion: v1
kind: Service
metadata:
  name: minio-external-ip
spec:
  ports:
  - name: minio
    port: 80
    protocol: TCP
    targetPort: 9769
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-external-ip
subsets:
- addresses:
  - ip: 192.168.1.27
  ports:
  - name: minio
    port: 9769
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-external-service
spec:
  rules:
  - host: minio.basingse.ca
    http:
      paths:
      - backend:
          serviceName: minio-external-ip
          servicePort: 80
        path: /
