apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr-external
  namespace: default
spec:
  target:
    name: unpackerr-external
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        UN_SONARR_0_API_KEY: |-
          {{ .UN_SONARR_0_API_KEY }}
        UN_RADARR_0_API_KEY: |-
          {{ .UN_RADARR_0_API_KEY }}
        UN_SONARR_1_API_KEY: |-
          {{ .UN_SONARR_1_API_KEY }}
        UN_RADARR_1_API_KEY: |-
          {{ .UN_RADARR_1_API_KEY }}
  data:
    - secretKey: UN_SONARR_0_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cc06fc224-f38a-40b9-b088-b3dc017a183a
        property: password
    - secretKey: UN_RADARR_0_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 8a71a48d-8e14-474b-99c2-b3dc017a4191
        property: password
    - secretKey: UN_SONARR_1_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: fa7a09b5-b818-4ef1-9cf8-b3dc017a8701
        property: password
    - secretKey: UN_RADARR_1_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 043b172c-f04c-42c0-b152-b3dc017ab5a0
        property: password
