---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpackerr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        containers:
          main:
            image:
              # -- image repository
              repository: ghcr.io/hotio/unpackerr
              # -- image tag
              # this example is not automatically updated, so be sure to use the latest image
              # https://hotio.dev/containers/unpackerr/#tags
              tag: latest@sha256:441fe1a9931cebe93bc24b5763679993ecb21d08d6f38b75d6b1e59661e8965f
              # -- image pull policy
              pullPolicy: IfNotPresent
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  exec:
                    command:
                      - ls
                      - /data/
                  initialDelaySeconds: 10
                  periodSeconds: 7200
                  failureThreshold: 1
                  timeoutSeconds: 5

            # -- environment variables.
            # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
            # requests:
            #   memory: 2048Mi
            #   cpu: 10m
            # limits:
            #   memory: 2048Mi
            env:
              UN_ACTIVITY: "true"
              TZ: "EST"
              UN_INTERVAL: 1m
              PUID: 1000
              PGUID: 1000
              UMASK: 002
              UN_WEBSERVER_METRICS: "true"
              UN_SONARR_0_URL: https://tv.lab.umaidabbasi.com
              UN_SONARR_0_PATHS_0: &path /data/torrents
              UN_RADARR_0_URL: https://movies.lab.umaidabbasi.com
              UN_RADARR_0_PATHS_0: *path
              UN_SONARR_1_URL: https://kidstv.lab.umaidabbasi.com
              UN_SONARR_1_PATHS_0: *path
              UN_RADARR_1_URL: https://kidsmovies.lab.umaidabbasi.com
              UN_RADARR_1_PATHS_0: *path
            envFrom:
              - secretRef:
                  name: *app

    # -- Configures service settings for the chart.
    service:
      main:
        controller: main
        ports:
          http:
            port: 5656

    # -- Configure persistence settings for the chart under this key.
    persistence:
      data:
        existingClaim: media-pvc
        globalMounts:
          - path: /data
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 1
        # fsGroupChangePolicy: OnRootMismatch
