---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app unpackerr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      unpackerr:
        type: deployment
        annotations:
          reloader.stakater.com/auto: 'true'
    image:
      repository: ghcr.io/hotio/unpackerr
      tag: latest@sha256:13b84daaf2632ccea9f008ee0e2a9f78b5f0d45856eaeb4ff12de2ce35234335
    env:
      UN_ACTIVITY: "true"
      UN_INTERVAL: 1m
      UN_WEBSERVER_METRICS: "true"
      UN_SONARR_0_URL: https://tv.lab.umaidabbasi.com
      UN_SONARR_0_PATHS_0: &path /data/torrents
      UN_RADARR_0_URL: https://movies.lab.umaidabbasi.com
      UN_RADARR_0_PATHS_0: *path
      UN_SONARR_1_URL: https://kidstv.lab.umaidabbasi.com
      UN_SONARR_1_PATHS_0: *path
      UN_RADARR_1_URL: https://kidsmovies.lab.umaidabbasi.com
      UN_RADARR_1_PATHS_0: *path
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        controller: *app  
        ports:
          http:
            port: 5656
    # serviceMonitor:
    #   main:
    #     enabled: false
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    persistence:
      media:
        enabled: true
        type: nfs
        server: "192.168.1.27"
        path: /data/
        globalMounts:
          - path: /data
    resources:
      requests:
        memory: 2048Mi
        cpu: 10m
      limits:
        memory: 2048Mi