---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpackerr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        containers:
          main:
            image:
              # -- image repository
              repository: ghcr.io/hotio/unpackerr
              # -- image tag
              # this example is not automatically updated, so be sure to use the latest image
              tag: latest@sha256:13b84daaf2632ccea9f008ee0e2a9f78b5f0d45856eaeb4ff12de2ce35234335
              # -- image pull policy
              pullPolicy: IfNotPresent
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  exec:
                    command:
                      - ls
                      - /data/torrents/
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  failureThreshold: 3
                  timeoutSeconds: 5

            # -- environment variables.
            # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
            # requests:
            #   memory: 2048Mi
            #   cpu: 10m
            # limits:
            #   memory: 2048Mi
            env:
              UN_ACTIVITY: "true"
              TZ: "EST"
              UN_INTERVAL: 1m
              UN_WEBSERVER_METRICS: "true"
              UN_SONARR_0_URL: https://tv.lab.umaidabbasi.com:443
              UN_SONARR_0_PATHS_0: &path /data/torrents
              UN_RADARR_0_URL: https://movies.lab.umaidabbasi.com:443
              UN_RADARR_0_PATHS_0: *path
              UN_SONARR_1_URL: https://kidstv.lab.umaidabbasi.com:443
              UN_SONARR_1_PATHS_0: *path
              UN_RADARR_1_URL: https://kidsmovies.lab.umaidabbasi.com:443
              UN_RADARR_1_PATHS_0: *path
            envFrom:
              - secretRef:
                  name: *app

    # -- Configures service settings for the chart.
    service:
      main:
        controller: main
        ports:
          http:
            port: 5656

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        type: nfs
        server: "192.168.1.27"
        path: /mnt/user/data
        globalMounts:
          - path: /data
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 1
        # fsGroupChangePolicy: OnRootMismatch
