apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: default
  annotations: 
    k8up.syn.tools/ignore: true
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # Arbitrary value, used just to match a persistent volume
  volumeName: media