apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  interval: 5m
  url: https://github.com/mdonoughe/porkbun-webhook
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !deploy/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  interval: 1m
  releaseName: porkbun-basingse
  chart:
    spec:
      chart: deploy/porkbun-webhook/
      sourceRef:
        kind: GitRepository
        name: porkbun-webhook
  values:
    groupName: basingse.ca 
