apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: homebridge
  name: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: homebridge
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: homebridge
    spec:
      hostNetwork: true
      containers:
        - image: oznu/homebridge:latest
          name: homebridge
          # volumeMounts:
          #   - mountPath: /homebridge
          #     name: homebridge-claim
      restartPolicy: Always
      # volumes:
      #   - name: homebridge-claim
      #     persistentVolumeClaim:
      #       claimName: homebridge-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homebridge
  name: homebridge-web
  namespace: default
spec:
  loadBalancerIP: 192.168.2.11
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8581
  selector:
    io.kompose.service: homebridge
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  labels:
    app: homebridge
  name: homebridge
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: homebridge.basingse.ca
    http:
      paths:
      - backend:
          service:
            name: homebridge-web
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - homebridge.basingse.ca
    secretName: homebridge-tls-secret
status:
  loadBalancer:
    ingress:
    - ip: 192.168.2.11