apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  chart:
    spec:
      version: "2.24.0"
  values:
    admin:
        existingSecret: pihole-password
        passwordKey: password
    # adminPassword: 
    #   valueFrom:
    #     secretKeyRef:
    #       name: pihole-password
    #       key: password
    serviceDns:
      loadBalancerIP: 192.168.2.13
      type: LoadBalancer
      mixedService: true
    serviceWeb:
      loadBalancerIP: 192.168.2.2
      type: ClusterIP
    persistentVolumeClaim:
      enabled: true
      storageClass: "local-path"
    dnsmasq:
      customDnsEntries:
        - address=/kind-k8s.lab/192.168.2.11
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - pihole.home-k8s.lab

