apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  chart:
    spec:
      version: "2.24.0"
  values:
    ingress:
      hosts:
        - host: pihole.production
          paths:
            - path: /
              pathType: ImplementationSpecific
