apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  chart:
    spec:
      version: "2.24.0"
  values:
    replicaCount: 1
    admin:
        existingSecret: pihole-password
        passwordKey: password
    serviceDns:
      loadBalancerIP: 192.168.2.13
      type: LoadBalancer
      mixedService: true
    serviceWeb:
      loadBalancerIP: 192.168.2.11
      type: ClusterIP
    persistentVolumeClaim:
      enabled: true
      storageClass: "local-path"
    dnsmasq:
      customDnsEntries:
        - address=/home-k8s.lab/192.168.2.11
    ingress:
      enabled: true
      ingressClassName: nginx
      path: /admin
      annotations:
        kubernetes.io/ingress.class: nginx 
        nginx.org/server-snippets: |
          location / {
            return 302 /admin;
          }  
      hosts:
        - pihole.home-k8s.lab

