apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  chart:
    spec:
      version: "2.24.0"
  values:
    replicaCount: 1
    admin:
        existingSecret: pihole-password
        passwordKey: password
    serviceDns:
      loadBalancerIP: 192.168.2.13
      type: LoadBalancer
      mixedService: true
    serviceWeb:
      loadBalancerIP: 192.168.2.11
      type: ClusterIP
    persistentVolumeClaim:
      enabled: true
      storageClass: "replicated-storage"
      # storageClass: "openebs-jiva-csi-default"
    dnsmasq:
      customDnsEntries:
        - address=/basingse.ca/192.168.2.11
    ingress:
      enabled: true
      ingressClassName: nginx
      path: /admin
      annotations:
        kubernetes.io/ingress.class: nginx 
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.org/server-snippets: |
          location / {
            return 302 /admin;
          }  
      hosts:
        - pihole.basingse.ca
      tls:
      - hosts:
        - pihole.basingse.ca
        secretName: pihole-tls-secret

