---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus
      version: 25.24.1
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    server:
      serverFiles:
          prometheus.yml:
            scrape_configs:
              - job_name: unraid-cadvisor
                scrape_interval: 5s
                static_configs:
                - targets:
                  - 192.168.1.27:8081
              - job_name: unraid-nodeexporter
                scrape_interval: 5s
                static_configs:
                - targets:
                  - 192.168.1.27:9100
              - job_name: opnsense-nodeexporter
                scrape_interval: 5s
                static_configs:
                - targets:
                  - 192.168.1.1:9100
