---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus
      version: 25.30.2
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    alertmanager:
      enabled: false
    server:
      persistentVolume:
        existingClaim: "prometheus-server-claim"
        storageClass: "replicated-storage"
        size: 10Gi
    extraScrapeConfigs: |
      - job_name: unraid-cadvisor
        scrape_interval: 5s
        static_configs:
          - targets:
            - 192.168.1.27:8081
      - job_name: unraid-nodeexporter
        scrape_interval: 5s
        static_configs:
          - targets:
            - 192.168.1.27:9100
      - job_name: opnsense-nodeexporter
        scrape_interval: 5s
        static_configs:
          - targets:
            - 192.168.1.1:9100
      - job_name: mayastor
        scrape_interval: 5s
        static_configs:
          - targets:
            - 192.168.2.2:9502
            - 192.168.2.3:9502
            - 192.168.2.4:9502
      - job_name: k8up
        scrape_interval: 5s
        static_configs:
          - targets:
            - k8up-metrics:8080
      - job_name: unpackerr
        scrape_interval: 1m
        static_configs:
          - targets: ["unpackerr.default.svc.cluster.local:5656"]
