apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: default
type: Opaque
stringData:
  password: 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
  username: git
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: workloads
  namespace: default
spec:
  interval: 5m
  url: https://github.com/umizoom/homek8s.git
  ref:
    branch: main
  secretRef:
    name: github-pat
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workloads
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: workloads
  path: "./workloads/orbital-sync"
  prune: true
  timeout: 1m