apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaptarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaptarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaptarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "100"
            - name: PUID
              value: "99"
            - name: TZ
              value: America/New_York
          image: chaptarr/chaptarr:0.9.929
          name: chaptarr
          ports:
            - containerPort: 8789
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: chaptarr-config
            - mountPath: /audiobooks
              name: chaptarr-media
              subPath: media/audio-books
            - mountPath: /ebooks
              name: chaptarr-media
              subPath: media/books
            - mountPath: /downloads
              name: chaptarr-media
              subPath: torrents
          livenessProbe:
            exec:
              command:
              - ls
              - /ebooks/
            initialDelaySeconds: 10
            periodSeconds: 7200
            failureThreshold: 1
            timeoutSeconds: 5
      restartPolicy: Always
      volumes:
        - name: chaptarr-config
          persistentVolumeClaim:
            claimName: chaptarr-config
        - name: chaptarr-media
          persistentVolumeClaim:
            claimName: media-pvc
