context: homecluster
contexts:
    homecluster:
        endpoints:
          - 192.168.2.2
          # - 192.168.2.3
        ca: ENC[AES256_GCM,data:R1toWRd27uUQRPIywEjTm//G82qoO/yo/OcRcxMY4WeE50rD1ZeaIafZNCWBf9PBTWYsN/H3bxANaG4shRFNAeZcYiUK4v+OgXMfnE84lX5KRQxEt8JGNbUfOQ2wXfU7ga0exj7OP1WMFTCSsuFlTVHkq3QH/I+Zt4niYpGv6nYWv2nJ5OfVrrx0KnxbTHpVYZH+6WB4Py3AOSQtpynxKyXabQXi26hbTtyB+Abrn6PWsUv5xOvG+me7NpW3UwbgVa7Psy97gGWCUZA2kzLKwFVzmBYXVpKY4+mAFi36sawD2v28sPNiATzl/1ZdDHk+ZdvvyHabsQSAc//7tkeu1PhrxKiIyO15D6QkB4LpjSY9QQx1ikG+sNpdpegkWZJpXtZEaqnlklFyBQWWDZqXrZ6XHSjuBPIA2bqxIYWv5Eb+XOnhYqncmz/Yp9fJP/ZOf01+4QETz2OFKweqW58q0fsKCjpNXwU5ZucKdtivKcSbE2BlyTHR5uiPIFY4CfH/AfPDrLp2DfkHeO0kjWceOaq4DbaGsI6fLlJjamcU/ZqvNbdQNsqrx/atqhdOcazsy5E8esnaM6YFs06QskN43iwOMp4iIZu1E21MqKdTPR1hti5fEdGzgrNnCj5LGzcUEAjRy7G0FCgvXNVrmehmDyXuEx6NtXBx3mFD+5wTD+VPjtBipQsEXlEe3osDX/+P3qWqyOzBVYAWo4Dsltn/0KABUvIEd8IA/3OCsqp5TUliccaBBz28dYC0jAYWLohKk/E7qxYSKNNpzEKPoZh1kpgZfVGUUW6eHIln9/n4yVMC07d6onHx1BtMsBZGDoIrhDLyncDG8xitbUy6HVaQ7IExDi9M9o0HM6LmFgR0n9bXAw5D,iv:3ReLsfQFQlSVO5stjzJBLUmnuawSI7l9d+cAa3YSODU=,tag:rYM/pff9x342TL6aCdJZUw==,type:str]
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLVENCM0tBREFnRUNBaEVBc05PZitMRFFINEVsZU90Uk50dWNPREFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qUXdOakV4TURNek1qVTJXaGNOTWpVd05qRXhNRE16TWpVMldqQVRNUkV3RHdZRApWUVFLRXdodmN6cGhaRzFwYmpBcU1BVUdBeXRsY0FNaEFPYVBhRVRBd29OT0FlNWoyK0FJYUtJdXM3NFluYno5CjFKc3BzODFNUGVLZ28wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVVCclVzNTdkQU9MM1laNkhhbWhPc1BMTGFSc1F3QlFZREsyVndBMEVBLzkyNQpWUlJHWi9FN2l6YzMwaE5xK2VZS0NyZDd6RGlIaDRZbWJOVEVGK2UrWm9sMi9sWGc0YTV5dm45TGFlVFozTnROCmZudUc3c2hNbmNrdXdQZVpCQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: ENC[AES256_GCM,data:T5/fAfhXup5xfpts9MotyQwNdZLW8tPEwzdD0t6L5UsBtvmLYG2GAHrYXjgo5jkzNGG9E7ZA2e3Q3v2Y8UjWVxzysm+yyxMOsNj3xoklQReiYXCq+J1GEmSMSo+hZkbISi9qMMfW1CCnMMMcU1r84Ngqn8Na/qN7P5JU8rzovSCGvPDeHTtyrjQ81IPCVKDNBp29yBoA0Smz+8kaAPuAZ3wVwwOcdqt+GY54nBwAuiYynJZU,iv:wzwVMBpKmwUUGqtQGWwWpb2mwO1RA8tJIQguhFmkL5M=,tag:eVtVctSqkkRCylmyqtrNPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-26T03:46:03Z"
    mac: ENC[AES256_GCM,data:0t9eTZliwOiw+wJgvHycAUZ5d22llGkzsjcvEbWJKAGzjbABOpMdZVPdnIUPxweGAcCrs8OjbIWUW04Q9THIF3olaus1tElIfuvV3aT6jQWP5actHcrjdt1sBjKwMRAJVhqSh8Cg+KiWz6fjli3wQP4J2j7TPya+id7mJU58C3M=,iv:eLz9hChd73/MkGMkmq4k9JqfeIlow5MFP4MY911Ff2M=,tag:T0kGEYbha0DVsXTiQYCRqg==,type:str]
    pgp:
        - created_at: "2024-06-26T03:46:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVxt8ZNZv4DAQ/+O/bScpNCbPzZpcx3zPwrVpUCRvfehF9SvQ/2fVnXOVrk
            8Z74M4OBpS1x9pu34Xdmy8J1oMoNEmhwjGZDsO2iuqTAdg/cf15hwYin21clgDuh
            MZktMtdkcZFMWa0NzgpHHDTOj+33KHFPqFl+tLToBNSh6Zg85/PAGarB4axZN7Bu
            DX7U8YgDT/LiVLDNvBccamE+GAoY96Whr21A/8rM9UgRl+BW9aJZ7iA3/qfXsT4z
            H2RjZxEConujAdTej70xfz+2hxIa9BkjejlMpFcmuCI7ZyyMnWjugH0tMcEEDS15
            wIbk3N826EqX0/67l56dX48KqlpHwljxpCXhHKL8OoNzW3pD/zqOFC07XbBgUERv
            AECMnj8WBeAzeenoYgqzr7CDxKjnbn7nnsdq+2+7xq1uZMhgXAl9gWHe0xC31u7Y
            SjNF1Hva4ySriDun61/yF6MPFydoMRJApSrbgJi5uaWNTAgauG1t6SuT+Bwm4ps8
            Kj0Bs8suQutTSS2xSy/eqeRFzyj0PGeny7mOk12p9OfYf9hQ2xXWO6vKUddZxKu0
            qSZRv+YOsq1c19ezKa0jtkB40mONQXdiaytKyGMZ/w/L9LweEpBBkjPYChxQw10y
            9lHjaiwHIt/mJEOdZXsabHdAA6B1A3wevFzl3ROcGfW7GpPxlBmTR24YbUBuJEfU
            aAEJAhC/DpOqjDugeImQ1USNvB7EyCXlY03JU5obwLQF1vCo7t25Q6L6z5WWZHsl
            LPLn+H4qmljk6oFayLMujFUJrqDknDxycqdeVaDIwajPfnJ+Zu58Xr7CRqEs87Rm
            eBWPPmi4zYTM
            =ggih
            -----END PGP MESSAGE-----
          fp: BAFBAF486E2E489700A8639C2B75A847B165ECC2
    encrypted_regex: (ca|cert|key|secret|token)$
    version: 3.8.1
