context: homecluster
contexts:
    homecluster:
        endpoints:
            - 192.168.2.2
            - 192.168.2.3
            - 192.168.2.4
        ca: ENC[AES256_GCM,data:LoNzfwjRFpSETbEjHfqb6wMMoX4/rQCBXo+LGb5fwD2DbdsWTpzxzlF08zhR/iE0dAmyQcHO4wGu0kRRDMmGoDvWeQN5+9b/U3JNxSi7zrEqKkY9ty1bFLX6+XRAt+ILBXh2Er/hOtFs0vvoM/03fGkvd/+ci3BxsUfWjah9d96icEuCWxg8vJLn6AJbRJcz/SylZfyxA4SwXy26rHgoEISKScVoapa7xUmwBMTsuZ5lu06EX97Oqevh1l/hE1XhwrM043DhHi1Em2btYLEd2glPGqJjeUw2NI4D21V3C3wgm/ocKGE7Z0NaBFMFYtr+iY1BiM8O/EiwRLg8FrQ4+pLGS2D1YZsoYp7qTmpJaOhSz3rw2MbpIJTE8/ORUW/WhhwNSN7rql1CD4ohgfZ5laMAW2HPU7aNmdL+pF0AtX/ThfEfEl7rx1iO5tKif6sonksBAc53v8SgFNywnK9SFNDYuh8Rp/76KI45pplmjdIee55t0jKndDYpO+8PAqjjDxss/jyXbBUIRnuZekT8QjjJzpxRiSIyLj3SWrEr/t934blqpr+xFQQvzdDj0nyrnd3ySMyz16PPQNmvzjnbatMO23UjpCZa7NMuaO5P4Owak1iaNrxnbDR3BNSY9s4QnTT7nPpemLIpjCHZURmnIMR+nLJlZF5VRATThl202h9Izu5mGbXboB+9E0q3AqhGfEJRxobmoFCBHMz4zMel5TrWqRsncW2s3RJlx38dG/gp831ezu1c2/H4O0IZLgP2kR3OKnSIOHDCZbl/T3j7rTvjR5eqkXBuqcZNgVDr88CiwPzzM7U4ZdrNIhiCnqSRUl4EYC2M925Mpk4Sg/gPyakokLNZ/idYkkhm6kKfcB7DKjca,iv:CzzniXb8rJQg1NCkGRTJba+biOUEXq/Hoe8fRJMSgqo=,tag:B5Mvx4eD/o8wgz0cZTP7aw==,type:str]
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLVENCM0tBREFnRUNBaEVBc05PZitMRFFINEVsZU90Uk50dWNPREFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qUXdOakV4TURNek1qVTJXaGNOTWpVd05qRXhNRE16TWpVMldqQVRNUkV3RHdZRApWUVFLRXdodmN6cGhaRzFwYmpBcU1BVUdBeXRsY0FNaEFPYVBhRVRBd29OT0FlNWoyK0FJYUtJdXM3NFluYno5CjFKc3BzODFNUGVLZ28wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVVCclVzNTdkQU9MM1laNkhhbWhPc1BMTGFSc1F3QlFZREsyVndBMEVBLzkyNQpWUlJHWi9FN2l6YzMwaE5xK2VZS0NyZDd6RGlIaDRZbWJOVEVGK2UrWm9sMi9sWGc0YTV5dm45TGFlVFozTnROCmZudUc3c2hNbmNrdXdQZVpCQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: ENC[AES256_GCM,data:eH3F/y5uV/g8MdDsqCqtrENhYzhfkSvY0pfwSHjEdej/29/NBTn+tFVtP17yCTChKAlysWtQz/9wBZ6mlB5NliAWmPyI3sXboDT9KJ2SMd2ffHUWNNzF0SVZFAwMpD9xlLpxCDUTeoVu6sryZ1cGyGuPv3E9nzOBtP0cFnO4i+/Zp+tnq6CmQOEWmGiUvR/+KkUGQWoIjIkz/vJUkw6cFJPXZlTGaOYP+7ubRYpSfYjdQvmq,iv:dZrujBgzQNrAHNH00jifu5diNxMqe//MkK+XEQeFod8=,tag:AnOjN2uJjivXN/9xX1A1rQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-16T03:09:30Z"
    mac: ENC[AES256_GCM,data:a4Gc5vjyd1kpdCMww+ldZapG48ZgylXZkKQKEQgf7VSiEXVGMV0TeJBMG8ldWR6b2hp/ZGsvsiKD+CEU+UGnTC6hS5wErQJG56w6Edw/ygBM6HSxWWpZCfJwqKug4fqtcH+QjEULbqxkqEPvdGe7YDVdTYNGtwitTezbITvic7c=,iv:QzaDXtU7TEZd1YPwf/vTP0MFXD3es5dyoNNaPFF+pxI=,tag:Z0AQvhR/IXpZJHr3tXeQUQ==,type:str]
    pgp:
        - created_at: "2024-07-16T03:09:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVxt8ZNZv4DAQ//fJLLM1HakDqDURZ0CdCTL1SMYS3zaYIOIsLEN+/UDg5O
            bq4dwX8GeyDCFn+betw34aKkwimdiPfFMlaZZE8VG29G2M9AqSBNT4gP1Z1l/h9N
            Vxsl0J6lnu/dBfVhoXfaR1lwz0S0GP8Zx5UieYAXarfKHBqqkZRKGwHXXl8eN7TX
            JWwURvnLsobm6eESkoXaErLNx42Rbq4eaHXX2kR6m4Cip5ooIUgc2st/cbJambbF
            qAXLlTYU8zb6TtxAStPAZgK+kmnYcxg0FaJlm6EgW9oSGkWuXaiv24Jm9/4DbKia
            Ub63NrD2XjTtjbf6e1PH59j8wOxOYPycCNKTJdkX8c+IPO0FETJ35ZOWWYElriMz
            coJRvJ8tQU67S6jLc4SNHp/E0s8yDYOP9k54b0VmanHT7/qEB8kCVnnVgE7ixDui
            0efusvb010iPzJLSP9KYQ+0kQp8NehJOpcVqqtrJqToF3o8Kxl89LxYjk1inExWv
            TJsL82NW5tMCMrE5wPFAUGoMKWT5OdodJ2Pv+Qeu5lT6/z++xwMcfis07yUGX6IN
            e0tZjvud4qq+VS4tnSilncaoIUkyAV3TsGjHHJmcfqesd7WsjZtghcglCZh6NpA4
            RwRWi78+rdT0sUMIh8UJz7/OOunvFAb/TqmAiTNDcgLGhhsRhnKfr4uFKMpoEGfU
            aAEJAhC99emqLwuzKRyPqasYPhrhjZtJIKc/3PwZbeuW8vOSCSXudBOsi3g1/RXR
            h9aeaJe5EFJn+jpro8NfNXn4md+A7dm3oO7zku+WFde1keoejZyC2GAIe+OpPt/m
            sBJ4lsrnn6R+
            =m8fc
            -----END PGP MESSAGE-----
          fp: BAFBAF486E2E489700A8639C2B75A847B165ECC2
    encrypted_regex: (ca|cert|key|secret|token)$
    version: 3.8.1
