context: homecluster
contexts:
    homecluster:
        endpoints:
            - 192.168.2.2
            - 192.168.2.3
            - 192.168.2.4
        ca: ENC[AES256_GCM,data:o5K5oodLdg9rustZUZG5xUdfGOc5vIGAbnNlebLU8HDp0prZxiGtgzwYgPAvOhyfenpcg/3mM4rgO7qzN5Cvt7O7q0zFBemFlkJZGjyOTFNtJRgsAkBueIovwSGn1VAGGgQFPs3audFvsei9GXosshObIdQRekIEQQWjfWdioTUPHVeBGZg9x70im07bxt/6IT77aKD+NiPBd/9xTG1tYgf7ivGER5N5hq6FVE2obDZgBi2kwPqmVSI0Ct2lG2bZxodlUrcSFoCrCryb9hsC+Iv3E8l5pV+gWALTD15aVg8X+lEP6SpXARA9o1iQcNfeS1SvV6svlA2Rn8Jy4G0jqP2pIaZ/wEDmgPmOjOllTfTfPiRFU1B5Ef+jU5x1fUWrr8TVWJypCGA1RjD9wcHQBghQhRjJgAhA+hZeg7Nsw0iUWg8Y7UDh0M9x/6MmSdbXEviwZKdlggW4L4KGe3qyVQc8hfSe2Yv9ULpQdB2edKNkndLvBoR89pmSDMOvtrhgaMHi7kx4a/0gvg6XpOW1ZhK9kK4fjWQpzWFwdaFf/tBq2wLgBN7/e2qLkE8ALUVLljax65KZSSnKNwQjikElX7UvDobtgTSO04FhpNt4NLXq9MWp35/GrUYNdcorSrsQg50K9QuVXCNy2fyfT+kvrm9SyRk9j1ZOPDmy2xSjyqdTTDV89Yf/GUEPLRcn0EGb8INluvZhLV577wODY05gWbljGu5ciBSogiI7T4KrVirEMyF9wKh+gNZLEysKvqwb8wE14Gs8xNXLUAzXZYTIy9K/+gtWLQ+kiqeTL/Q0vApSTbQyIeCeyB4yGD+4KzA/ziaLbGAzVi9Qlex+CJkvNyRV2RJFiVA86xcAjpxrLtnEkkzD,iv:WF8YX4/ZQcdNh6ivV0xQB3hvFQtkl67qjiamJa3k5tg=,tag:+o2LQ/uVlKFm0ZUIyZisNA==,type:str]
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJPakNCN2FBREFnRUNBaEVBOVJRdU1LU0J6OTVwUGt2MnZvdnJDREFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXdOakV5TVRZMU9EUTBXaGNOTWpZd05qRXlNVFkxT0RRMFdqQVRNUkV3RHdZRApWUVFLRXdodmN6cGhaRzFwYmpBcU1BVUdBeXRsY0FNaEFLNElrd3lQOWUyWjNkTjlWRVRiekFWVFpqZVRvS29DCmx6Z0Z5d1Niai9MU28xa3dWekFPQmdOVkhROEJBZjhFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVVCclVzNTdkQU9MM1laNkhhbWhPc1BMTGFSc1F3RHdZRFZSMFJCQWd3Qm9jRQpmd0FBQVRBRkJnTXJaWEFEUVFETVJWRmtKOCtNWXMrVWVsY3J3Y3B2aTd0RG55d3BEK0loWnI4a015Q3FPZVc5CmFUazVQTUk5MjBLWUVlMDlONktzZUxTQmlBWlFsK09JeEtTSHFuOFAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        key: ENC[AES256_GCM,data:Xpn4579T4hhh6aTCz/IMuw4ctEmp+vrgvxXsri/yBFuSZrRKS8KGgxf/1+9whYUXvEsN7sjEXHASsvkPk1yZczS8VFsznLFwd40iR6VlXCUwlpnAv0LC2csvyl7Q7ik0losPiyEhHgSM3NhPYAwm6GN7dw8t63emOiXnpkF6TYsUJ0LZ5ZpQPo1xWJ25wt1p1qQSx4fp9+lKazExq1a5h0SzOziW6zf0125oedmqCvYYvYe/,iv:m3LdDSIdv6FRrvx2WgHY5dM2SD0w6gHfpuKHx18rYQg=,tag:ukgNwZKBnKbTZYrZnjNwHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-12T17:42:12Z"
    mac: ENC[AES256_GCM,data:Go24e90pu72p/wsAliGnKV8SKc7sSDw8GRRUW27hphUzvHZca5lHQsDJPMgyGMmg6xVHxGsqvOSd2NlfYCdxbb222//kRa4NKyr3Thac6xxEJO0XXWeCGwcJEfiMOCpiKW7NuPTmlO45Su4ogvGTf2/z+v+TXKq8ZZXKm7VmPwo=,iv:774U/YIp2BxXvcetzyeFlekpg4tAlv5oRXOzhKjC4LA=,tag:+/RV88pL+YTWegmfqjbwOA==,type:str]
    pgp:
        - created_at: "2025-06-12T17:42:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVxt8ZNZv4DAQ//WibZ9lvDL4IrpnVrTfIMII2p68D2uyAAZa9llncPHM/H
            yDSAXTj2Ew3tlIDkmF9Mzi0wm7GNC+q6bX+LegV3VVZdQoUFgi8ixasE2Zl18epj
            j4gHNAqnUP8hEJvjXVqFxJUbL+05biMfUbD1tWBdcoBITIkWaTQlOHKyTc1hexWk
            29zPTiBoUMdwHgEJbR9svGyLab+3C0BkuGmORJ/Z+I9AzxnYaf6YX0koynpSL2/3
            ax1S7zFDEENn50eL4jkyHPnC3QeNlLhiI753cgJwE9Kpa5tXsyOgWY8CgVB3JBMX
            6S+TVjXTo//lHieMtWPrS98FdaRM6ezt1b/oYyOwsdjfxWWiMQd4Ow/FXAi+G5cA
            9lggAy6s07/CqdQHLc/AaNhWYvJAFXbSnafJZwwWcSe1/W8hJj+lS3J7RP2iAAU+
            S0K88SAp5Ojy+QaDdtw0XWlZumM6CVfRI1Sj0E5uCmvEDKsi0T5LOVpZlhEJkZ1y
            8sziU9P9qvlwbGQ6g47hLsY4ejTskF3oTlS4Uf6itoAfPDrHNgq/kV3RALrxzRn3
            fb6slF+d4eVj8Ddvnv3PUvClo8IwGQypNKmJf7nw+UPi2GiT3K7tdTvWh8GX/YuI
            eTViehAWG8+55UB/BVse8TK79jshZXV9j2QnY8ENk3lOXY2tPGwCYyLeuovHXT3U
            aAEJAhCMuS7nYJr4lfdFFe2Wu75x1zDUt3BZsixUoC7kXIs4WKssuEXVMDxWUWbW
            jEVztV3sGUu1QnCLl5mKPO3qoqcs02NcqDjo2r0ODSanLgwBlYhBaFdylNoa3MAU
            rJeYxSqQXGz9
            =CQUI
            -----END PGP MESSAGE-----
          fp: BAFBAF486E2E489700A8639C2B75A847B165ECC2
    encrypted_regex: (ca|cert|key|secret|token)$
    version: 3.8.1
