apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-reaper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-reaper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pod-reaper
    spec:
      serviceAccountName: pod-reaper-sa
      containers:
        - env:
            - name: inCluster
              value: "true"
            - name: TIMEZONE
              value: "EST"
          image: ghcr.io/umizoom/pod-reaper:latest@sha256:da71fb0535d6fa4971771c6a2632d649bc2aa5a309cdebb105c7a8843620761d
          name: pod-reaper
      restartPolicy: Always

