apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reaper-sa
  namespace: default 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: pod-reaper-role
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["list", "delete", "get", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reaper-role
subjects:
  - kind: ServiceAccount
    name: pod-reaper-sa
    namespace: default
