apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../base/metrics-server
patches:
#   - path: metrics-server.yaml
#     target:
#       kind: Deployment
    - patch: |-
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --kubelet-insecure-tls
      target:
        kind: Deployment
