apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/MoJo2600/pihole-kubernetes/blob/main/charts/pihole/values.yaml
  values:
    # enables cloudflare tunnel sidecar container
    # and sets upstream dns in pihole to leverage it
    adminPassword: "umaid"
    doh:
      enabled: true
      pullPolicy: Always
      envVars: {
        DOH_UPSTREAM: "https://1.1.1.1/dns-query"
      }
    ingress:
      enabled: true
      className: nginx
