apiVersion: v1
kind: Service
metadata:
  name: calibre-web
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8083
  selector:
    app: calibre-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.org/client-max-body-size: "0"
  labels:
    app: calibre-web
  name: calibre-web
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: books.basingse.ca
    http:
      paths:
      - backend:
          service:
            name: calibre-web
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - books.basingse.ca
    secretName: calibre-web-tls-secret
status:
  loadBalancer:
    ingress:
    - ip: 192.168.2.11