apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
spec:
  storageClassName: "replicated-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-books
spec:
  storageClassName: "replicated-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
