apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password-external
  namespace: default
spec:
  target:
    name: pihole-password-external
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        password: |-
          {{ .password }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: e3208355-ccd7-42ca-9f87-b3dc017557c0
        property: password
