apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 5Gi # Arbitrary value
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=4.1
  nfs:
    path: /mnt/user/data   # Path to the existing NFS directory
    server: 192.168.1.27