{
 "title": "Unpackerr",
 "description": "Official Unpackerr Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "starrUrl",
    "query": {
     "query": "label_values(unpackerr_app_queue_size{instance=\"$instance\"},url)"
    }
   },
   {
    "name": "instance",
    "label": "Unpackerr",
    "query": {
     "query": "label_values(unpackerr_counters,instance)"
    }
   },
   {
    "name": "source",
    "query": {
     "query": "label_values(unpackerr_archives_read_total{instance=\"$instance\"},url)"
    }
   },
   {
    "name": "interval",
    "label": "Poll Interval",
    "query": "15s,30s,1m,90s,2m,3m,4m,5m,10m,15m,30m"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": {
    "content": "<br>\n<center><h2>Uptime</h2>\n[[instance]]</center>"
   }
  },
  {
   "type": "stat",
   "description": "How long unpackerr has been running",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "unpackerr_uptime_seconds_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Queue Gauges",
   "type": "timeseries",
   "description": "Contains counts for all Unpackerr queue gauges. As items progress through the queue, they transition from one of these states to another.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "unpackerr_gauges{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Counters",
   "type": "timeseries",
   "description": "Displays totals for all Unpackerr queue counters. Contains command hooks, web hooks, finished and retried extraction counts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by(name) (unpackerr_counters{instance=\"$instance\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Starr Queues",
   "type": "timeseries",
   "description": "Shows the number of items in the activity queue for each starr app that Unpackerr is polling.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(app, url) (unpackerr_app_queue_size{instance=\"$instance\"})",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Queue Buffers",
   "type": "timeseries",
   "description": "Contains channel buffer sizes. Under normal conditions these are always zero, or very close to zero.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "unpackerr_buffers{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Starr API Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "API Responses: [[starrUrl]]",
   "type": "timeseries",
   "description": "Visualization of API responses times from [[starrUrl]] and also includes request + error counts.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "repeat": "starrUrl",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "unpackerr_app_queue_fetch_time_seconds{url=\"$starrUrl\", instance=\"$instance\"}",
     "legendFormat": "{{app}} {{url}}"
    },
    {
     "expr": "increase(unpackerr_app_queue_fetch_total{url=\"$starrUrl\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Requests"
    },
    {
     "expr": "increase(unpackerr_app_queue_fetch_errors_total{url=\"$starrUrl\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Xtracts: [[source]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "source" },
  {
   "title": "Bytes Written",
   "type": "stat",
   "description": "This is how many bytes have been written from extracted archives via source: [[source]]",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unpackerr_bytes_written_total{instance=\"$instance\", url=\"$source\"}",
     "legendFormat": "{{url}}"
    },
    {}
   ]
  },
  {
   "title": "Archives Read",
   "type": "stat",
   "description": "This is how many archive files (rar/zip/etc) that have been extracted via source: [[source]]",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unpackerr_archives_read_total{instance=\"$instance\", url=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FIles Extracted",
   "type": "stat",
   "description": "This is how many files that have been extracted and written to disk via source: [[source]]",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unpackerr_files_extracted_total{instance=\"$instance\", url=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extraction Duration: [[source]]",
   "type": "heatmap",
   "description": "This histogram depicts the duration of each extraction. Each extraction generally represents 1 item in a starr app, or 1 folder in a folder watcher. This may include any number of archives. Via source: [[source]]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "increase(unpackerr_extract_time_seconds_bucket{instance=\"$instance\", url=\"$source\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}