apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pia-creds-external
  namespace: default
spec:
  target:
    name: pia-creds-external
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: c334a679-4595-4271-a9d0-b3dc01761c7b
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: c334a679-4595-4271-a9d0-b3dc01761c7b
        property: password
