apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9696
  selector:
    io.kompose.service: prowlarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.org/location-snippets: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
  labels:
    app: prowlarr
  name: prowlarr
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: indexer.basingse.ca
    http:
      paths:
      - backend:
          service:
            name: prowlarr
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - indexer.basingse.ca
    secretName: prowlarr-tls-secret
status:
  loadBalancer:
    ingress:
    - ip: 192.168.2.11