apiVersion: v1
kind: Secret
metadata:
    name: pihole-unraid
    namespace: default
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:7/xBY/1eDa226PMi3w9heo+OwVyfrlyEiw0lWSTILzqllYufE6TX8zSuisHaiMTkeVe/PEbm6nDK57Zn6qIXdC87vuvEae0CIER40A==,iv:eccAgP7wOSqRGhSX3+VY81sjjsCBus+oiP90Mb0wEco=,tag:cJffSJA5jV7PIYYHioXfJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-13T00:21:28Z"
    mac: ENC[AES256_GCM,data:G4LaHW0BjjZBhFbXt3I884aZ2HPLgWbOnU+yrmc6dbmLfhC6cBQw9F8e8voVE8IFpVjBuzFHDsEKu7ClB4tBmuJRo3O1wGgAqLww5uUkDVjPJBa93HJd5qV3fhfZMRZF6t16ClFAO1U/xQpuanCllFmQQutgNIPGv2O89usoKdw=,iv:yH83qVZSD/xiYuAxgTNBgRZdogb4fuWqZ698eufbZAM=,tag:4Dsp9LRh3yNmYrmqWr7EIA==,type:str]
    pgp:
        - created_at: "2025-06-13T00:21:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVxt8ZNZv4DARAAnhiRaoXoQMW0We4zD+riin8QHpWiOasiXZcDx6PNSOkz
            FQR8AZrdU40BTnc+zhOc5WkipruKFmKUME5slYvckNGr/jNJW83Zd3TvrtNMkuei
            56Is7hW4tU+Ua0gQDAroz3tE9cVMBpmCAnT99R7eun3XsT4QeXdFXcYMCCHCmf6y
            cEH3E5P0s8NtpMXU8Wmh1RDx/xfyQsHNfDWrwid2tX6cXtMij3lpC9uEKHAbPKIp
            kUeffc9EatZfEuKg1W7wcNkOGm7qSEiqeMLvRUVlV/fRxSnP09aBhpr+5ASuSse/
            QtWLSgfzoUZK4O1CEaR9Y6ijFK80osIv0+OJwLJRLDYpA4cBw8VHmYwrs/an5dEC
            6w7kT3cYkyawCd/wYV5zoX3SWKGMzPnRmVzAWz82mOSLKvDw1qqre45T0buKMwpH
            ZunLnBuYY9OmwOtGfM2iiWq6a6l3mmanqzEbgM1YTs62YOHdmJ0r2f3ullNC37QX
            UWHi9SsJRJdeQE9HTVC4wGcl31zAS9UcY4nbBxPer1jn9t2XtU8et3lZY8BIyK1r
            AsC6uoP9YerF6R0UklhqKMPfxzdsXG7xlPxqvSdobdDybQZroBkzzboxZ/dpICXB
            D6cloxnmsxo/fZURrNaLlEMTgO0JGZyyMdqMsJrYKcimUpO3YcgYJUdeCgNK5fbU
            ZgEJAhCN4ydCdA4xHXlYaahrtJTUiOe+6tZ5yXHJ806Bt22UECpSziAL0dS/fWus
            zXtFmuyFHYHuk91d2JRckC3cmYLMEE6gWGiZTYYx6EugxGV2mu3mpOIcmEZMzA9A
            49xREZ00bg==
            =F5w5
            -----END PGP MESSAGE-----
          fp: BAFBAF486E2E489700A8639C2B75A847B165ECC2
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pihole-k8s
    namespace: default
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:YzIyjTfo8b7jfy7lKMuYntFPFuIg1nUD31dkco31cCb76r7uUuPvVkH4rUYtKHOJFM07RftPUBtzotokmQhw+9xCkX+ooOg=,iv:4/fN9AnDNqwP50+TCfd6MrAl9Q/Ija5rVZuvAuGEROo=,tag:i5dzhwhL8uMuxr2Chez1zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-13T00:21:28Z"
    mac: ENC[AES256_GCM,data:G4LaHW0BjjZBhFbXt3I884aZ2HPLgWbOnU+yrmc6dbmLfhC6cBQw9F8e8voVE8IFpVjBuzFHDsEKu7ClB4tBmuJRo3O1wGgAqLww5uUkDVjPJBa93HJd5qV3fhfZMRZF6t16ClFAO1U/xQpuanCllFmQQutgNIPGv2O89usoKdw=,iv:yH83qVZSD/xiYuAxgTNBgRZdogb4fuWqZ698eufbZAM=,tag:4Dsp9LRh3yNmYrmqWr7EIA==,type:str]
    pgp:
        - created_at: "2025-06-13T00:21:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVxt8ZNZv4DARAAnhiRaoXoQMW0We4zD+riin8QHpWiOasiXZcDx6PNSOkz
            FQR8AZrdU40BTnc+zhOc5WkipruKFmKUME5slYvckNGr/jNJW83Zd3TvrtNMkuei
            56Is7hW4tU+Ua0gQDAroz3tE9cVMBpmCAnT99R7eun3XsT4QeXdFXcYMCCHCmf6y
            cEH3E5P0s8NtpMXU8Wmh1RDx/xfyQsHNfDWrwid2tX6cXtMij3lpC9uEKHAbPKIp
            kUeffc9EatZfEuKg1W7wcNkOGm7qSEiqeMLvRUVlV/fRxSnP09aBhpr+5ASuSse/
            QtWLSgfzoUZK4O1CEaR9Y6ijFK80osIv0+OJwLJRLDYpA4cBw8VHmYwrs/an5dEC
            6w7kT3cYkyawCd/wYV5zoX3SWKGMzPnRmVzAWz82mOSLKvDw1qqre45T0buKMwpH
            ZunLnBuYY9OmwOtGfM2iiWq6a6l3mmanqzEbgM1YTs62YOHdmJ0r2f3ullNC37QX
            UWHi9SsJRJdeQE9HTVC4wGcl31zAS9UcY4nbBxPer1jn9t2XtU8et3lZY8BIyK1r
            AsC6uoP9YerF6R0UklhqKMPfxzdsXG7xlPxqvSdobdDybQZroBkzzboxZ/dpICXB
            D6cloxnmsxo/fZURrNaLlEMTgO0JGZyyMdqMsJrYKcimUpO3YcgYJUdeCgNK5fbU
            ZgEJAhCN4ydCdA4xHXlYaahrtJTUiOe+6tZ5yXHJ806Bt22UECpSziAL0dS/fWus
            zXtFmuyFHYHuk91d2JRckC3cmYLMEE6gWGiZTYYx6EugxGV2mu3mpOIcmEZMzA9A
            49xREZ00bg==
            =F5w5
            -----END PGP MESSAGE-----
          fp: BAFBAF486E2E489700A8639C2B75A847B165ECC2
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
