apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: ConfigMap
metadata:
  name: openebs
  namespace: openebs
spec:  
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: ConfigMap
              name: '.*-csi-iscsiadm'
            patch: |
              - op: replace
                path: /data/iscsiadm
                value: |
                  #!/bin/sh
                  iscsid_pid=$(pgrep iscsid)
                  nsenter --mount="/proc/${iscsid_pid}/ns/mnt" --net="/proc/${iscsid_pid}/ns/net" -- /usr/local/sbin/iscsiadm "$@"