apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  url: https://github.com/openebs-archive/jiva-operator
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !deploy/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: deploy/helm/charts
      sourceRef:
        kind: GitRepository
        name: openebs
