apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  url: https://github.com/openebs-archive/jiva-operator
  ref:
    branch: v3.6.x
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !deploy/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: deploy/helm/charts
      sourceRef:
        kind: GitRepository
        name: openebs
  # Required: Must enable hostPID for JIVA to work on Talos
  # https://www.talos.dev/v1.2/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: DaemonSet
              name: openebs-jiva-csi-node
            patch:
              - op: add
                path: /spec/template/spec/hostPID
                value: true
          - target:
              kind: ConfigMap
              name: openebs-jiva-csi-iscsiadm
            patch:
              - op: replace
                path: /data/iscsiadm
                value: |
                  #!/bin/sh
                  iscsid_pid=$(pgrep iscsid)

                  nsenter --mount="/proc/${iscsid_pid}/ns/mnt" --net="/proc/${iscsid_pid}/ns/net" -- /usr/local/sbin/iscsiadm "$@"
