apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/nfs-subdir-external
patches:
  - path: nfs-subdir-external.yaml
    target:
      namespace: nfs-provisioner
      kind: HelmRelease


